resources_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: 0.12.2

resources:
  - name: git-repo
    type: git
    source:
      uri: git@github.com:jessicastenning/concourse-pipelines.git
      branch: master
      private_key: ((deploy_key))

  - name: terraform
    type: terraform
    source:
      backend_type: s3
      backend_config:
        bucket: mybucket
        key: mydir/terraform.tfstate
        region: us-east-1
        access_key: ((concourse_ci_s3_access_key))
        secret_key: ((concourse_ci_s3_secret_key))
      vars:
        tag_name: concourse
      env:
        AWS_ACCESS_KEY_ID: ((concourse_ci_s3_access_key))
        AWS_SECRET_ACCESS_KEY: ((concourse_ci_s3_secret_key))
        AWS_DEFAULT_REGION: ((aws_region))
