resources_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: 0.12.2

resources:
  - name: git-repo
    type: git
    source:
      uri: git@github.com:jessicastenning/concourse-pipelines.git
      branch: master
      private_key: ((deploy_key))
  - name: tfstate-bucket
    type: s3
    source:
      region_name: ((aws_region))
      bucket: tfstate-bucket
      versioned_file: ci/terraform.tfstate
      access_key_id: ((concourse_ci_s3_access_key))
      secret_access_key: ((concourse_ci_s3_secret_key))
  - name: terraform
    type: terraform
    source:
      backend_type: s3
      backend_config:
        bucket: mybucket
        key: mydir/terraform.tfstate
        region: us-east-1
        access_key: ((concourse_ci_s3_access_key))
        secret_key: ((concourse_ci_s3_secret_key))
      vars:
        tag_name: concourse
      env:
        AWS_ACCESS_KEY_ID: ((concourse_ci_s3_access_key))
        AWS_SECRET_ACCESS_KEY: ((concourse_ci_s3_secret_key))
        AWS_DEFAULT_REGION: ((aws_region))

jobs:
- name: create_state_bucket
  plan:
  - get: git-repo
    trigger: true
  - task: create_state_bucket
    file: concourse-pipelines/tasks/create_state_bucket.yml
    params:
      AWS_ACCESS_KEY_ID: ((concourse_ci_s3_access_key))
      AWS_SECRET_ACCESS_KEY: ((concourse_ci_s3_secret_key))
  - put: tfstate-bucket
    params:
      file: tfstate-out/terraform.tfstate
